name: 'Terraform'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  dev:
    name: 'Terraform dev'
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.head.ref == 'dev'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra

      - name: Terraform Init
        run: terraform init -backend-config="region=us-west-1"
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Plan (dev)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: terraform plan -input=false -var-file=env/dev/terraform.tfvars
        working-directory: infra

      # Apply para dev (us-west-1)
      - name: Terraform Apply (dev)
        if: github.event.pull_request.base.ref == 'dev'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: terraform apply -auto-approve -input=false -var-file=env/dev/terraform.tfvars
        working-directory: infra

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge from dev branch'
          title: 'PR: Merge from dev branch'
          body: 'PR criado automaticamente.'
          base: main
          branch: auto/pr-branch

  main:
    name: 'Terraform Prod'
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Init
        if: github.event.pull_request.base.ref == 'main'
        run: terraform init -backend-config="region=us-east-1"
        working-directory: infra

      - name: Terraform Plan (prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform plan -input=false -var-file=env/prod/terraform.tfvars
        working-directory: infra

      # Apply para prod (us-east-1)
      - name: Terraform Apply (prod)
        if: github.event.pull_request.base.ref == 'prod'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform apply -auto-approve -input=false -var-file=env/prod/terraform.tfvars
        working-directory: infra
